require 'user.options'
require 'user.keymaps'
require 'user.plugins'
require 'user.autocommands'
require 'user.lualine'
require 'user.lsp'
require 'user.treesitter'
require 'user.toggleterm'
require 'user.colorscheme'
require 'user.cmp'
require 'user.gitsigns'
require 'user.indentline'
require 'user.comment'
require 'user.impatient'
require 'user.telescope'
require 'user.comment'

vim.cmd 'source ~/.config/nvim/old_config.vim'
