[[profile]]
name = "laptop builtin"
  [[profile.output]]
  match = "eDP-1"
  enable = true

[[profile]]
name = "HomeOffice"
  [[profile.output]]
  match = "eDP-1"
  enable = false

  [[profile.output]]
  match = "/.*DELL S2721DS D3K2R43.*/"
  enable = true
  transform = "90"
  position = { x=0, y=0}
  adaptive_sync = true
  [[profile.output]]
  match = "/.*M32QC 21390B000953.*/"
  enable = true
  position = { x=1440, y=500}
  adaptive_sync = true
